/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.97.0
  Forc version: 0.66.4
  Fuel-Core version: 0.40.1
*/

import {
  BigNumberish,
  BN,
  Bytes,
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
  StdString,
} from 'fuels';

export type PredicateStdLibStringConfigurables = undefined;

export type PredicateStdLibStringInputs = [_arg_0: BigNumberish, _arg_1: BigNumberish, arg_2: StdString];

export type PredicateStdLibStringParameters = Omit<
  PredicateParams<PredicateStdLibStringInputs, PredicateStdLibStringConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "struct std::string::String",
      "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "metadataTypeId": 3
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 0
    },
    {
      "type": "struct std::bytes::Bytes",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "buf",
          "typeId": 2
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::bytes::RawBytes",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "ptr",
          "typeId": 0
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::string::String",
      "metadataTypeId": 3,
      "components": [
        {
          "name": "bytes",
          "typeId": 1
        }
      ]
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "_arg_0",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "_arg_1",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "arg_2",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA31VS2gTURS9mSZt/WAeRIs8EEetOn4ZtNbufCGZprGNfaENrWCciooKUeuowZ3BtYsq+MGVCxcuR6j7WbrM0mVdCAYbcFNocRHPe5NgTcYGwjze3HPvuZ9zh/+y6RGRQfo3YJVbQYy1WsRXJb0gevJAUN81x6BUnlF1gvq9CTJSzu5aNUuxUSCupY2LwMfw3Ok2aafM+Au8QWSun6X53yuG/L0Sx/sRnqtTxP1pPhl5b/HpOskZn3mzNGgVE8Jt2n04M6vpCNzf1ueZz6JcJGKFbOCmbULsMW8K95nlQE77pvLLv9vdvg/wTJ3KBSJgY+U0GXLOn4D/bW5TbEcOO3iDAWcS/ya7sZcUdlgQvSLa/3oQ/lEnnnlPPLdC5Tx85k3t25M0yArnSPHia/C1wegt7N8Ad3Fd45928KizHfpYIj65QuDOgGdWIYHa9PDfp2pzZApYuUh7SjZVZymG+0RYn4Tgcz6VS5Ks4myA3ExvHvelRI03evLZrvJxHYG/HXMdMvgao5eKz4bZ4fu0zXdgE1/WyRnzgJjxGs8gZppifI0Unm3KdyDEJ1t/8bGAZ2rEr6NmuV8Gc1ggJ/119G6vlY8H6ONb3kDNvvfMxTvduzLqfBm9K6F3Gd92m6zfy9IOPAdQO4EzahcXeCf1OT0iFDeZ8xc0X2ekVnYYIeYiMLvQ86QnVB7DaoZ+aExmWcAeNVMzxP7h8ZjonubhqH63Z2j6E4Ovg27TPAR/w/Djq95F5HAnAmsBexjYI8Aejej581APn6CDRdguHHOb8jhviG67Z3ymTinMXaqA2BLcK0TVKRpHjHlgTwB7EthTETEeqhhDheWAS2h9Ss/UGHBL4HYG3M6C2wi09yXMy4c+euK3eWJ+b6CGxVEB/KI+F8ZFRMxKO6+P4HYO3EbB7by85X9VuYUxlnp5IkfYmN5t+L05XgO+ps/F1+hXD6eZ7pogN4Pd9QX6mOVrAvOKedyotec12YrQ59hmfeo5bcYD/tPvjnXwP9pMQYd7t9DhfjUTsEFvRQK7qD/CZojP1ckqxYO/erU7eh2L0Gtfz37CrCl9btJm3xa22FuRtlvuAYVLpUlURfh9gA6SV9q+ovcCXYjeg9gP0+BRJGOolBWqjqnwmcJ8mXrX4bvQ3W/09IyqJUtD/zmfuavMUPFlkSWv4luhdZ7frXcyahp3V9t3k8v6Ltx9dofjBcUxhzwmblYq9825+17lRvip1L/4hz8vzfMVQAcAAA==');

export class PredicateStdLibString extends Predicate<
  PredicateStdLibStringInputs,
  PredicateStdLibStringConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: PredicateStdLibStringParameters) {
    super({ abi, bytecode, ...params });
  }
}
